# Generated by Django 5.2.12 on 2026-03-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='segments_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
