# Generated by Django 4.2.7 on 2026-03-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_segments_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='countries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
