# Generated by Django 4.2.7 on 2026-04-08 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivered_at_order_delivery_email_sent_and_more'),
        ('reports', '0003_report_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255)),
                ('plan_type', models.CharField(default='professional', max_length=20)),
                ('is_demo', models.BooleanField(default=False)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_logs', to='orders.order')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='reports.report')),
            ],
            options={
                'verbose_name': 'Report Download Log',
                'verbose_name_plural': 'Report Download Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
