# Generated by Django 4.2.7 on 2026-03-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='base_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='order',
            name='countries_list',
            field=models.TextField(blank=True, help_text='Comma separated list of countries'),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='forecast_year',
            field=models.IntegerField(default=2033),
        ),
        migrations.AddField(
            model_name='order',
            name='has_segmentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='metric',
            field=models.CharField(default='Revenue (USD Million)', max_length=50),
        ),
    ]
