# Generated by Django 4.2.7 on 2026-03-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_country_price', models.PositiveIntegerField(default=20, help_text='Price per country selection ($)')),
                ('global_price', models.PositiveIntegerField(default=20, help_text='Price for Global Market Size ($)')),
                ('segmentation_price', models.PositiveIntegerField(default=99, help_text='Flat fee for 3-Level Segmentation ($)')),
                ('pro_cap', models.PositiveIntegerField(default=199, help_text='Auto-cap when 10+ countries selected ($)')),
                ('pro_cap_threshold', models.PositiveIntegerField(default=10, help_text='Number of countries to trigger Professional cap')),
                ('enterprise_cap', models.PositiveIntegerField(default=299, help_text='Auto-cap for countries + segmentation ($)')),
                ('extra_country_price', models.PositiveIntegerField(default=20, help_text='Per extra custom country beyond cap ($)')),
                ('both_metric_multiplier', models.DecimalField(decimal_places=1, default=2.0, help_text='Multiplier when Revenue + Volume is selected', max_digits=3)),
                ('min_order', models.PositiveIntegerField(default=20, help_text='Minimum order amount ($)')),
            ],
            options={
                'verbose_name': 'Pricing Settings',
                'verbose_name_plural': 'Pricing Settings',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=True, help_text='Shown by default in the builder')),
                ('is_rest_of', models.BooleanField(default=False, help_text='Is a "Rest of" aggregate (dashed style)')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='pricing.region')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['display_order'],
            },
        ),
    ]
