# Generated by Django 4.2.7 on 2026-03-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsettings',
            name='paypal_client_id',
            field=models.CharField(blank=True, help_text='PayPal Client ID', max_length=255),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='stripe_public_key',
            field=models.CharField(blank=True, help_text='Stripe Publishable Key', max_length=255),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='stripe_secret_key',
            field=models.CharField(blank=True, help_text='Stripe Secret Key', max_length=255),
        ),
    ]
