# Generated by Django 4.2.7 on 2026-03-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Emoji icon', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tag strings, e.g. ["TAM","CAGR"]')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'How It Works Step',
                'verbose_name_plural': 'How It Works Steps',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('scroll_target', models.CharField(blank=True, help_text='Section ID to scroll to, e.g. how-sec', max_length=100)),
                ('url', models.CharField(blank=True, help_text='External URL (overrides scroll_target)', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_cta', models.BooleanField(default=False, help_text='Styled as primary CTA button')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PricingExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(max_length=200)),
                ('price', models.CharField(help_text='e.g. $20, $199', max_length=20)),
                ('calculation', models.CharField(help_text='e.g. 1 country × $20', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Forecastly.io', max_length=100)),
                ('tagline', models.CharField(default='Market Intelligence', max_length=200)),
                ('hero_title', models.TextField(default='Analyst-verified <span class="accent">Excel datasheets</span> for any market — starting at $20')),
                ('hero_subtitle', models.TextField(default='13-country breakdowns, 3-level segmentation, and 10-year forecasts — validated by our research analysts and delivered to your inbox within 60 minutes.')),
                ('hero_search_placeholder', models.CharField(default='Enter any market — e.g., Electric Vehicle Battery, AI in Healthcare ...', max_length=200)),
                ('hero_hint_text', models.CharField(default='Try: Renewable Energy Storage, Cybersecurity, Digital Therapeutics, Semiconductor', max_length=300)),
                ('hero_badge_text', models.CharField(default='📊 Market Size Estimates & Forecasts in Excel', max_length=200)),
                ('dark_cta_title', models.CharField(default='Your analyst-verified market report, delivered in 60 minutes.', max_length=300)),
                ('dark_cta_text', models.TextField(default='No RFPs. No 6-week timelines. No $5,000 invoices. Download a free demo Excel right now to see the exact report structure — no payment required.')),
                ('dark_cta_button_text', models.CharField(default='Download Free Demo Excel →', max_length=100)),
                ('dark_cta_note', models.CharField(default='FREE DEMO INSTANTLY · FROM $20/COUNTRY · AUTO-CAPS AT $199/$299 · ANALYST-VERIFIED', max_length=300)),
                ('footer_text', models.CharField(default='© 2026 Forecastly.io', max_length=200)),
                ('excel_preview_title', models.CharField(default='Global Renewable Energy Storage Market, 2025–2033 (USD Million)', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Emoji icon, e.g. 🔬', max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('sublabel', models.CharField(blank=True, max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Emoji icon', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
