# Generated by Django 4.2.7 on 2026-03-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_refine_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='support_chat_hours',
            field=models.CharField(default='Mon–Fri, 9AM–6PM EST', help_text='Live chat availability hours', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_email',
            field=models.CharField(default='support@forecastly.io', help_text='Support email displayed on dashboard', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_phone',
            field=models.CharField(default='+1 (800) 555-0199', help_text='Support phone number', max_length=100),
        ),
    ]
