# Generated by Django 4.2.7 on 2026-04-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_sitesettings_support_chat_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=250)),
                ('blog_content', models.TextField()),
                ('meta_title', models.CharField(blank=True, max_length=250)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('latest_or_oldest', models.CharField(choices=[('latest', 'Latest'), ('oldest', 'Oldest')], default='latest', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='support_email',
            field=models.CharField(default='hello@estimately.io', help_text='Support email displayed on dashboard', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='support_phone',
            field=models.CharField(default='+1-970-633-3460', help_text='Support phone number', max_length=100),
        ),
    ]
