# Generated by Django 4.2.7 on 2026-04-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_blog_alter_sitesettings_support_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='latest_or_oldest',
        ),
    ]
