# Generated by Django 5.2.13 on 2026-04-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_blog_latest_or_oldest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='support_email',
            field=models.CharField(default='hello@Estimately.io', help_text='Support email displayed on dashboard', max_length=200),
        ),
    ]
